### ISSUE TITLE
Object CoG offset modification

### ISSUE THREAD

**Issue by claracharreau** [DorisSupport/NI_Twin#12]
When I want to change the CoG offset of a created object and push the button "save", it does not save my new values.

1. Click on the object
2. Click on 'Edit Object'
1. Go to 'Generic Object settings'
3. Modify the CoG
4. Click on 'Save'
5. Close the window and reopen it, no motivation has occurred

 - OS: Windows
 - Browser: Microsoft Edge

**Comment by DorisSupport** [comment]
This is a known issue, that needs to be updated.
To correctly apply the modifications, you need to type "ENTER" after modifying the values.
A complete rework of the OBJECTs editing window is planned that will fix this and provide a better user experience.
