### ISSUE TITLE
OBS trouble

### ISSUE THREAD

**Issue by Greg-LYG** [DorisSupport/NI_Twin#13]
It seems that the socket is badly attached to wire (picture 2).
it seems that the wire doesn't rotate like the sheave (picture 1).
![image](https://github.com/user-attachments/assets/0875b7d4-d1d9-49af-8e13-1b2bf57ab85e)

![image](https://github.com/user-attachments/assets/1788ac10-c3f4-4283-8233-a546e88f828c)

**Comment by DorisSupport** [comment]
Problem has been solved in latest release.
