### ISSUE TITLE
Container on Keel Ref0 Frame

### ISSUE THREAD

**Issue by David-SBM** [DorisSupport/NI_Twin#7]
There is a container at (0,0,0) reference frame of the vessel

![Container_ref0](https://github.com/user-attachments/assets/4aef7f64-bd3f-49ee-9d74-d489255d3d49)

**Comment by DorisSupport** [comment]
I just realized this too! And I found the source of this behaviour. The container appears when you hit the "i" key on your keyboard.
I reloved the faulty code, this will be online with the next update (tomorrow 20/09/2024)

**Comment by DorisSupport** [comment]
I just realized this too! And I found the source of this behaviour. The container appears when you hit the "i" key on your keyboard.
I reloved the faulty code, this will be online with the next update (tomorrow 20/09/2024)
